### ISSUE TITLE
g3_fit()$params is a list, not a data.frame

### ISSUE THREAD

**Issue by MikkoVihtakari** [gadget-framework/gadgetutils#12]
I noticed that `g3_iterative()` returns a list as `$params` element now, not a data.frame/tibble as it used to do previously. Also, there are still no bounds in that could be used to check whether estimates exceed their bounds.

Can you reproduce this problem or is it due to some weird setup from my end?

The list instead of data.frame breaks many gadgetplots functions. Is there a reason to return a list? I.e. should I modify gadgetplots or should we return list using switch as column name for parameters instead?

**Comment by MikkoVihtakari** [comment]
Partly related to this perhaps: https://github.com/gadget-framework/gadgetplots/pull/1

But the fix does not help, because there is no `fit$params$value` currently. Modifying the fix would not be a problem if there is a reason for returning a list instead of a data frame.

**Comment by willbutler42** [comment]
Looking into this now. Do you mean `g3_fit()`? 

If so, `g3_fit `returns the params in the form they are entered. So if the params argument is a list it will return a list, whereas if it is a df it will return the df. If you provide the list (i.e. params$value) we could convert it to a data.frame but we will not know the values of lower and upper, so would have to set these to NA or something, this is the reason for returning the list.

**Comment by MikkoVihtakari** [comment]
Yes, sorry, I meant `g3_fit()`. 

`g3_fit(model, g3_tmb_relist(tmb_param, optim_param$par))` here: https://github.com/DeepWaterIMR/ghl-gadget3/blob/67a2f8f60962439e30e28313a68fe4a8a00374bc/_RUN_THE_MODEL.R#L162

**Comment by lentinj** [comment]
My vote would be for ``g3_fit`` always returning the ``params$value`` list. It's remit is to munge the output of a gadget3 model and return more consistent data structures, so in keeping with this it should choose one form to stick with it. As you say, turning a list back into a data.frame is impossible, so it has to be the list. Which presumably is the interesting bit for gadgetplots anyway.

**Comment by MikkoVihtakari** [comment]
Yup, format is not important as far as it is consistent, *but* we'll need to carry the bound information onward from `attr(tmb_model, "parameter_template")` somehow. Those are needed in model diagnostics to see which parameters exceed their boundaries. That would mean that the list would have multiple columns or elements. Hence data.frame was a natural choice here.

**Comment by willbutler42** [comment]
> `g3_fit(model, g3_tmb_relist(tmb_param, optim_param$par))`

I have created a wrapper for stats::optim which should help with this. You provide the tmb_model and tmb_params (and other arguments to optim) and it will return the parameter dataframe with optimised values (i.e. g3_tmb_adfun, optim, and g3_tmb_relist, parts are done internally).I will update your script Mikko

**Comment by MikkoVihtakari** [comment]
To add to the discussion with Jamie, sometimes we have switch column which contains the parameter names, other times row names or list element names. We'll need to be consistent to make grep work on the names.

**Comment by willbutler42** [comment]
Yes, a useful diagnostic is to plot the optimised values relative to the bounds which wouldn't be possible returning `params$value`. For consistency we could insist that the `params` argument to `g3_fit() `is always a data.frame?

**Comment by MikkoVihtakari** [comment]
I would go for the first option (but am not entirely qualified to form an opinion). It would be best to always return consistent structures from a function (i.e. that input would not influence the class of output).

**Comment by MikkoVihtakari** [comment]
Fixed now.
