### ISSUE TITLE
g3_iterative to return a SS table

### ISSUE THREAD

**Issue by bthe** [gadget-framework/gadgetutils#13]
`g3_iterative` should save individual likelihood component scores for each model run in a table (analogous to Rgadget SS table).

**Comment by willbutler42** [comment]
Likelihood component scores (and the normalised ones) are now written to the iterative folder ('lik.comp.score' and 'lik.comp.score.norm'), see [ae21cf9](https://github.com/gadget-framework/gadgetutils/commit/ae21cf9e46c2471a5a94d5d6f1b6ae1872966dc0)
