### ISSUE TITLE
g3_fit calculates the fishing mortality incorrecly 

### ISSUE THREAD

**Issue by bthe** [gadget-framework/gadgetutils#18]
Fishing mortality by predator is calculated using the formulation:
```
F = -log(1 - catch/biomass)/dt 
``` 
where `dt` is the length of the timestep. In `g3_fit` a quarterly timestep is assumed, that is `dt`  is equal to  1/4 (see here https://github.com/gadget-framework/gadgetutils/blob/main/R/g3_fit.R#L322 ). This is obviously not ideal for models with other time step sizes.

**Comment by willbutler42** [comment]
A rather painful error, fixed here:
[5922532](https://github.com/gadget-framework/gadgetutils/commit/59225321c9261f593fd085ee6325dfc0d3dc5bde)
