### ISSUE TITLE
g3_iterative - resume final behaves incorrectly

### ISSUE THREAD

**Issue by bthe** [gadget-framework/gadgetutils#19]
In `g3_iterative`, the `resume_final` appears not to start based on the results from the first step of the iterative heuristic.

**Comment by willbutler42** [comment]
This is been fixed here [085bd4d](https://github.com/gadget-framework/gadgetutils/commit/085bd4d358f746d521f3d66be0c803f3e8aa2520). If `resume_final = TRUE`, the optimised parameters from stage 1 are loaded and the second stage of optimisation is resumed. If the stage 1 optimised parameters are not found, an error is issued.
