### ISSUE TITLE
add jitter option to gadget iterative

### ISSUE THREAD

**Issue by willbutler42** [gadget-framework/gadgetutils#3]
Include an option to jitter the parameters in gadget iterative. This should probably occur at the second stage of re-weighting and as many times as cores are available (with a sensible default for when not running parallel).

**Comment by daniel-howell** [comment]
This can be done on the final model, with the final weighting. If the model is robust to the jitter then we can assume that the weighting runs were also robust.

**Comment by bthe** [comment]
This is mostly implement now using `g3_jitter` which is then passed into `g3_optim`. Here is an example of how to run the optimization in parallel:

```
 params_jitter <- 
    parallel::mclapply(1:100,
                       function(x) {
                         params <- g3_jitter(params_final)
                         g3_optim(tmb_model, 
                                  params,
                                  use_parscale = TRUE,
                                  print_status = TRUE)
                       }, mc.cores = parallel::detectCores())
```

This could be wrapped into a special function generates a new

**Comment by willbutler42** [comment]
This has been updated in [6a61b90](https://github.com/gadget-framework/gadgetutils/commit/6a61b901e44249f541992468d48723b280528356) so `g3_jitter` is now a wrapper for the optimisation too. `g3_jitter` calls jitter_params to create a list of jitter initial parameters, and then calls `g3_optim` to optimise each set of jittered parameters (see `?g3_jitter` for details)
