### ISSUE TITLE
plots for g3 fit objects

### ISSUE THREAD

**Issue by willbutler42** [gadget-framework/gadgetutils#4]
Instead of using the plot.gadget.fit template, have a series of unique plotting functions, for example, plot_biomass, plot_renewal etc. Wrappers can then be used for convenience, e.g. annual_plots for the 'ICES' plots. Ideally these functions would be able to take in multiple fit objects to contrast models.

**Comment by MikkoVihtakari** [comment]
Good idea. I can help you making these changes.

**Comment by MikkoVihtakari** [comment]
Done here: https://github.com/gadget-framework/gadgetplots
