### ISSUE TITLE
data option for g3_init_guess

### ISSUE THREAD

**Issue by willbutler42** [gadget-framework/gadgetutils#6]
Expand g3_init_guess so that inital values can be taken from a data frame. Would be useful for time- or age-varying parameters.

**Comment by lentinj** [comment]
``g3_init_val`` in https://github.com/gadget-framework/gadget3/issues/124 can set a vector of values, e.g.:

```
g3_init_val(pt, '*.rec.[1993-1996]', value = c(3,4,5,6))
```

This isn't quite data.frame support, since you don't match the ``1993`` row with the corresponding value. You're just assuming that the rows are ``1993--1996``.

**Comment by willbutler42** [comment]
Great, that will do the trick :)
